# Generated by Django 6.0.7 on 2026-09-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeylogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('device_id', models.CharField(max_length=200)),
                ('page', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('buffer', models.TextField()),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
